# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a75tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/73474/Desktop/M0/LCD/vivado/CortexM0_SoC/CortexM0_SoC.cache/wt [current_project]
set_property parent.project_path C:/Users/73474/Desktop/M0/LCD/vivado/CortexM0_SoC/CortexM0_SoC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/73474/Desktop/M0/LCD/vivado/CortexM0_SoC/CortexM0_SoC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/73474/Desktop/M0/LCD/rtl/AHBlite_Block_RAM.v
  C:/Users/73474/Desktop/M0/LCD/rtl/AHBlite_Decoder.v
  C:/Users/73474/Desktop/M0/LCD/rtl/AHBlite_Interconnect.v
  C:/Users/73474/Desktop/M0/LCD/rtl/AHBlite_Keyboard.v
  C:/Users/73474/Desktop/M0/LCD/rtl/AHBlite_LCD.v
  C:/Users/73474/Desktop/M0/LCD/rtl/AHBlite_SlaveMUX.v
  C:/Users/73474/Desktop/M0/LCD/rtl/AddrCounter.v
  C:/Users/73474/Desktop/M0/LCD/rtl/AddrIni.v
  C:/Users/73474/Desktop/M0/LCD/rtl/BlockROM1.v
  C:/Users/73474/Desktop/M0/LCD/rtl/BlockROM16.v
  C:/Users/73474/Desktop/M0/LCD/rtl/Block_RAM.v
  C:/Users/73474/Desktop/M0/LCD/rtl/DataTrans.v
  C:/Users/73474/Desktop/M0/LCD/rtl/Keyboard.v
  C:/Users/73474/Desktop/M0/LCD/rtl/LCD.v
  C:/Users/73474/Desktop/M0/LCD/rtl/LCDCtrl.v
  C:/Users/73474/Desktop/M0/LCD/rtl/WriteCtrl.v
  C:/Users/73474/Desktop/M0/LCD/rtl/cortexm0ds_logic.v
  C:/Users/73474/Desktop/M0/LCD/rtl/keyboard_filter.v
  C:/Users/73474/Desktop/M0/LCD/rtl/keyboard_reg.v
  C:/Users/73474/Desktop/M0/LCD/rtl/keyboard_scan.v
  C:/Users/73474/Desktop/M0/LCD/rtl/CortexM0_SoC.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/73474/Desktop/M0/LCD/vivado/pin.xdc
set_property used_in_implementation false [get_files C:/Users/73474/Desktop/M0/LCD/vivado/pin.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top CortexM0_SoC -part xc7a75tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CortexM0_SoC.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CortexM0_SoC_utilization_synth.rpt -pb CortexM0_SoC_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
